module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'jsdom',
  setupFilesAfterEnv: ['<rootDir>/src/setupTests.ts'],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '\\.(css|less|scss|sass)$': 'identity-obj-proxy',
    '^@/config/environment$': '<rootDir>/src/config/__mocks__/environment.ts',
    '^../config/environment$': '<rootDir>/src/config/__mocks__/environment.ts',
    '^.*/config/environment$': '<rootDir>/src/config/__mocks__/environment.ts',
    '^@/utils/logger$': '<rootDir>/src/utils/__mocks__/logger.ts',
    '^../utils/logger$': '<rootDir>/src/utils/__mocks__/logger.ts',
    '^.*/utils/logger$': '<rootDir>/src/utils/__mocks__/logger.ts',
    '^@/config/monitoring$': '<rootDir>/src/config/__mocks__/monitoring.ts',
    '^../config/monitoring$': '<rootDir>/src/config/__mocks__/monitoring.ts',
    '^.*/config/monitoring$': '<rootDir>/src/config/__mocks__/monitoring.ts',
    '^@/services/printNodeService$': '<rootDir>/src/services/__mocks__/printNodeService.ts',
    '^../services/printNodeService$': '<rootDir>/src/services/__mocks__/printNodeService.ts',
    '^.*/services/printNodeService$': '<rootDir>/src/services/__mocks__/printNodeService.ts',
    '^@/lib/supabase$': '<rootDir>/src/lib/__mocks__/supabase.ts',
    '^../lib/supabase$': '<rootDir>/src/lib/__mocks__/supabase.ts',
    '^.*/lib/supabase$': '<rootDir>/src/lib/__mocks__/supabase.ts',
    '^@/shared/components/LazyComponents$': '<rootDir>/src/shared/components/__mocks__/LazyComponents.ts',
    '^../LazyComponents$': '<rootDir>/src/shared/components/__mocks__/LazyComponents.ts',
    '^.*/LazyComponents$': '<rootDir>/src/shared/components/__mocks__/LazyComponents.ts',
    '^@/components/ui/Toast$': '<rootDir>/src/shared/components/ui/__mocks__/Toast.ts',
    '^../components/ui/Toast$': '<rootDir>/src/shared/components/ui/__mocks__/Toast.ts',
    '^.*/components/ui/Toast$': '<rootDir>/src/shared/components/ui/__mocks__/Toast.ts',
  },
  transform: {
    '^.+\\.(ts|tsx)$': ['ts-jest', {
      tsconfig: 'tsconfig.test.json',
      useESM: false,
      isolatedModules: true
    }],
  },
  testMatch: [
    '<rootDir>/src/**/__tests__/**/*.(ts|tsx)',
    '<rootDir>/src/**/*.(test|spec).(ts|tsx)',
  ],
  collectCoverageFrom: [
    'src/**/*.{ts,tsx}',
    '!src/**/*.d.ts',
    '!src/main.tsx',
    '!src/vite-env.d.ts',
    '!src/setupTests.ts',
    '!src/**/__tests__/**',
    '!src/**/*.test.{ts,tsx}',
    '!src/**/*.spec.{ts,tsx}',
  ],
  coverageThreshold: {
    global: {
      branches: 70,
      functions: 70,
      lines: 70,
      statements: 70,
    },
  },
  coverageReporters: ['text', 'lcov', 'html'],
  testTimeout: 10000,
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json'],
  transformIgnorePatterns: [
    'node_modules/(?!(.*\\.mjs$))',
  ],
};